site_name: Certificação AZ-900
site_author: woliversor
theme:
  name: readthedocs  # ou 'material' se já instalou
  language: pt
nav:
  - Início: Apostila.md
extra_css:
  - custom.css
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - codehilite
  - attr_list
  - pymdownx.superfences
  - pymdownx.tabbed
